[build]
  publish = "public"
  command = "hugo"
  #command = "hugo --gc --minify"
  #command = "yarn tinacms build && hugo --gc --minify"

  [build.environment]
    #HUGO_VERSION = "0.92.0"
    HUGO_VERSION = "0.123.4"
    

[context.production.environment]
  HUGO_ENV           = "production"
  HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "hugo --gc --minify --enableGitInfo"

  [context.split1.environment]
    HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from   = "http://pumo.io/*"
  to     = "https://pumo.io/"
  status = 301
  force = true #COMMENT: ensure that we always redirect
